# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

jobs:
- job: Build_iOS
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'
  - script: |
      cd RNDemoCICD
      yarn install
    displayName: Install dependency
  - script: |
      cd RNDemoCICD/ios
      pod install
    displayName: Install cocoapods

  - script: fastlane dev
    displayName: Test, Build and publish app by fastlane 
