# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- dev

pool:
  vmImage: 'macos-latest'

jobs:
- job: Build_iOS
  steps:
  - script: fastlane dev p12_pw:$(P12_PW)
    displayName: Running Build