# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

jobs:
- job: Build_iOS
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'
  - script: |
      cd RNDemoCICD
      yarn install
    displayName: Install dependency
  - script: |
      cd RNDemoCICD/ios
      pod install
    displayName: Install cocoapods

  - script: | 
      cd RNDemoCICD/ios
      fastlane dev
    displayName: Test, Build and publish app by fastlane 
- job: Build_Android
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11' 
      jdkArchitectureOption: x64
      jdkSourceOption: 'PreInstalled'
  - script: |
      cd RNDemoCICD
      yarn install
    displayName: Install dependency
  - script: |
      cd RNDemoCICD/android
      fastlane dev
    displayName: Test, Build and publish app by fastlane 