# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Beta"
  lane :dev do

    increment_version_code(
      gradle_file_path: "app/build.gradle",
    )

    gradle(task: "clean assembleDebug")

    appcenter_upload(
      api_token: "14c1509d6505cb523455b547cd49db0a6d7e367f",
      owner_name: "CI-React-Native-Example",
      owner_type: "organization",#"user", # Default is user - set to organization for appcenter organizations
      app_name: "CI-RN-Android",
      notify_testers: false # Set to false if you don't want to notify testers of your new release (default: `false`)
    )

    # git_commit(path: "app/build.gradle", message: "Version Bump")
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

end
