# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :dev do
    # add actions here: https://docs.fastlane.tools/actions
    puts "Run from fastlane"

    install_provisioning_profile(path: "configs/DemoAppAdhoc.mobileprovision")
    
    create_keychain(
      name: "CICD_Keychain3",
      password: "password",
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )

    import_certificate(
      certificate_path: "configs/DisCertificates170622.p12",
      certificate_password: "smd@123",
      keychain_password: "password",
      keychain_name: "CICD_Keychain3"
    )

    increment_version_number_in_xcodeproj(version_number: "1.0.1")

        # run_tests(
    #   scheme: "CICDiOSProject",
    #   result_bundle: true
    # )

    gym(
      workspace: "RNDemoCICD.xcworkspace",
      scheme: "RNDemoCICD",
      export_method: "ad-hoc",
      export_options: {
        provisioningProfiles: {
          "com.smartdev.demoapp" => "DemoApp-Adhoc"
        },
        teamID: "XJ8Q6Z2QA7",
        compileBitcode: false,
        signingStyle: "manual"
      },
      clean: true
    )

    appcenter_upload(
      api_token: "14c1509d6505cb523455b547cd49db0a6d7e367f",
      owner_name: "CI-Example",
      owner_type: "organization",#"user", # Default is user - set to organization for appcenter organizations
      app_name: "CI-Example-iOS", #file: "CICDiOSProject.ipa",
      notify_testers: false # Set to false if you don't want to notify testers of your new release (default: `false`)
    )

  end
end
