name: Demo Android workflows

on: [push]

jobs:
  build_android:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: yarn install
        run: |
          cd RNDemoCICD
          yarn install
      - name: Test, Build and distribute to appcenter
        run: |
          cd RNDemoCICD/android
          fastlane dev
      
